-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.category
(
    id integer NOT NULL DEFAULT nextval('category_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.image
(
    id integer NOT NULL DEFAULT nextval('image_id_seq'::regclass),
    file_name character varying(255) COLLATE pg_catalog."default",
    product_id integer NOT NULL,
    CONSTRAINT image_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_person
(
    id integer NOT NULL DEFAULT nextval('order_person_id_seq'::regclass),
    date_time timestamp(6) without time zone,
    opnumber character varying(255) COLLATE pg_catalog."default",
    opsumm real,
    status smallint,
    person_id integer NOT NULL,
    CONSTRAINT order_person_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.person
(
    id integer NOT NULL DEFAULT nextval('person_id_seq'::regclass),
    login character varying(100) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT person_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    id integer NOT NULL DEFAULT nextval('product_id_seq'::regclass),
    date_time timestamp(6) without time zone,
    description text COLLATE pg_catalog."default" NOT NULL,
    price real NOT NULL,
    seller character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    category_id integer NOT NULL,
    warehouse_id integer NOT NULL,
    CONSTRAINT product_pkey PRIMARY KEY (id),
    CONSTRAINT uk_qka6vxqdy1dprtqnx9trdd47c UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS public.product_cart
(
    id integer NOT NULL DEFAULT nextval('product_cart_id_seq'::regclass),
    person_id integer,
    product_id integer,
    CONSTRAINT product_cart_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.warehouse
(
    id integer NOT NULL DEFAULT nextval('warehouse_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT warehouse_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."оrder_product"
(
    id integer NOT NULL DEFAULT nextval('"оrder_product_id_seq"'::regclass),
    count integer NOT NULL,
    date_time timestamp(6) without time zone,
    price real NOT NULL,
    order_person_id integer NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT "оrder_product_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.image
    ADD CONSTRAINT fkgpextbyee3uk9u6o2381m7ft1 FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_person
    ADD CONSTRAINT fkep8v4imh31iqqdxnt5isiuhq2 FOREIGN KEY (person_id)
    REFERENCES public.person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT fk1mtsbur82frn64de7balymq9s FOREIGN KEY (category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT fkk6edvfdkq61mjhltx856ncs3x FOREIGN KEY (warehouse_id)
    REFERENCES public.warehouse (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_cart
    ADD CONSTRAINT fkhpnrxdy3jhujameyod08ilvvw FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_cart
    ADD CONSTRAINT fksgnkc1ko2i1o9yr2p63ysq3rn FOREIGN KEY (person_id)
    REFERENCES public.person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."оrder_product"
    ADD CONSTRAINT fk1myga43hex2dg2205f0gb03d6 FOREIGN KEY (order_person_id)
    REFERENCES public.order_person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."оrder_product"
    ADD CONSTRAINT fkmob21icn6xkupe0baqw5iw892 FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;